cp $HOME/.config/picom .config/ -r
cp $HOME/.config/alacritty .config/ -r
cp $HOME/.config/nvim .config/ -r
cp $HOME/.config/sxhkd .config/ -r
cp $HOME/.config/pipewire .config/ -r
cp $HOME/.config/fish .config/ -r
cp $HOME/.config/tmux/tmux.conf .config/tmux -r
cp $HOME/.scripts ./ -r
cp $HOME/.xinitrc ./ -r
