#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         1
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# startup
wmname LG3D &
feh --bg-max --randomize ~/Pictures/wallpaper/* &
sh ~/.config/polybar/launch.sh
