#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
bspc monitor -d 1 2 3 4 5 &
feh --no-xinerama --bg-fill --randomize ~/Pictures/wallpaper/* &
sh ~/.config/polybar/launch.sh &