require("mini.pick").setup()
require("mini.extra").setup()

vim.keymap.set("n", "<leader>ff", function()
  require("mini.pick").builtin.files()
end, { desc = "Mini File Picker" })
vim.keymap.set("n", "<leader>fw", function()
  require("mini.pick").builtin.grep({ pattern = vim.fn.expand("<cword>") })
end, { desc = "Grep word/Search word" })
vim.keymap.set("n", "<leader>fh", function()
  require("mini.pick").builtin.help()
end, { desc = "Mini Help" })
vim.keymap.set("n", "<leader>fd", function()
  require("mini.extra").pickers.diagnostic()
end, { desc = "Mini Picker Diagnostics" })
vim.keymap.set("n", "<leader>fk", function()
  require("mini.extra").pickers.keymaps()
end, { desc = "Search keymaps" })
vim.keymap.set("n", "<leader>fr", function()
  require("mini.pick").builtin.resume()
end, { desc = "Mini Resume" })

vim.keymap.set("n", "<leader>fb", function()
  require("mini.pick").builtin.buffers()
end, { desc = "Mini Buffer Picker" })
vim.keymap.set("n", "<leader>fc", function()
  require("mini.pick").builtin.commands()
end, { desc = "Mini Command Picker" })
vim.keymap.set("n","<leader>fo",function()
  require("mini.pick").builtin.oldfiles()
end, { desc = "Mini Oldfiles Picker" })
