backend = "glx"
glx-no-stencil = true;
glx-copy-from-front = false;

# Opacity
active-opacity = 0.95;
inactive-opacity = 0.8;

# Blur
blur-background = true;
blur-method = "dual_kawase";
blur-strength = 12;

# Corner
corner-radius = 8;
detect-rounded-corners = true;

rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'Rofi'",
  "class_g = 'Dunst'"
];

