backend = "glx"

# Opacity
active-opacity = 0.95;
inactive-opacity = 0.8;

# Blur
blur-background = true;
blur-method = "dual_kawase";
blur-strength = 10;

# Corner
corner-radius = 4;
detect-rounded-corners = true;

vsync = true;

rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'Rofi'",
  "class_g = 'Dunst'"
];

