local SmartSplits = require("smart-splits")
SmartSplits.setup()
vim.keymap.set("n", "<C-A-h>", SmartSplits.resize_left)
vim.keymap.set("n", "<C-A-j>", SmartSplits.resize_down)
vim.keymap.set("n", "<C-A-k>", SmartSplits.resize_up)
vim.keymap.set("n", "<C-A-l>", SmartSplits.resize_right)
vim.keymap.set("n", "<C-h>", SmartSplits.move_cursor_left)
vim.keymap.set("n", "<C-j>", SmartSplits.move_cursor_down)
vim.keymap.set("n", "<C-k>", SmartSplits.move_cursor_up)
vim.keymap.set("n", "<C-l>", SmartSplits.move_cursor_right)
vim.keymap.set("n", "<C-\\>", SmartSplits.move_cursor_previous)
vim.keymap.set("n", "<leader><leader>h", SmartSplits.swap_buf_left)
vim.keymap.set("n", "<leader><leader>j", SmartSplits.swap_buf_down)
vim.keymap.set("n", "<leader><leader>k", SmartSplits.swap_buf_up)
vim.keymap.set("n", "<leader><leader>l", SmartSplits.swap_buf_right)
