# Default colors
[colors.primary]
background = '#011423'
foreground = '#CBE0F0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

[colors.normal]
black = "#214969"
red = "#E52E2E"
green = "#44FFB1"
yellow = "#FFE073"
blue = "#0FC5ED"
magenta = "#a277ff"
cyan = "#24EAF7"
white = "#24EAF7"

[colors.bright]
black = "#214969"
red = "#E52E2E"
green = "#44FFB1"
yellow = "#FFE073"
blue = "#A277FF"
magenta = "#a277ff"
cyan = "#24EAF7"
white = "#24EAF7"

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.8 
decorations = "Buttonless"

[font]
normal.family = "MonaspiceNe NF"

#regular
size = 12

#for video
# size = 35.0
